  - label: ":parcel::docker: Build Test container"
    concurrency: 1
    concurrency_group: "build_test_container"
    command: docker build -f Dockerfile.dev -t pycololight-devimage .

  - wait

  - label: ":python: Run Tests"
    command: pytest --cov=pycololight
    plugins:
      - docker#v3.5.0:
          image: "pycololight-devimage"
          workdir: /workspaces/pycololight

  - block: ":rotating_light::rocket: Release"
    branches: 'main'

  - label: ":parcel::python: Build"
    branches: 'main'
    command: ./scripts/build.sh
    plugins:
      - docker#v3.5.0:
          image: "pycololight-devimage"
          workdir: /workspaces/pycololight
    artifact_paths:
      - "dist/**/*"

  - wait

  - label: ":rocket::python: Publish to Pypi"
    branches: 'main'
    commands:
      - buildkite-agent artifact download dist/* .
      - poetry publish --username __token__ --password $PYPI_TOKEN
    plugins:
      - docker#v3.5.0:
          image: "pycololight-devimage"
          workdir: /workspaces/pycololight

  - label: ":rocket::github: Publish to github"
    branches: 'main'
    command: ./scripts/release_gh.sh