COMMAND_PREFIX = "535a30300000000000"

CUSTOM_EFFECT_COLOURS = {
    "Breath": {
        "decimal": 128,
        "colours": (
            "Red, Green, Blue",
            "Rainbow",
            "Green",
            "Azure",
            "Blue",
            "Purple",
            "Red",
            "Orange",
            "Yellow",
            "White",
            "Green, Blue",
        ),
    },
    "Shadow": {
        "decimal": 138,
        "colours": (
            "Red, Yellow",
            "Red, Green",
            "Red, Purple",
            "Red, Blue",
            "Green, Yellow",
            "Green, Azure",
            "Green, Blue",
            "Blue, Azure",
            "Blue, Purple",
            "Yellow, White",
            "Red, White",
            "Green, White",
            "Azure, White",
            "Blue, White",
            "Purple, White",
        ),
    },
    "Flash": {
        "decimal": 153,
        "colours": (
            "Red, Green, Blue",
            "Rainbow",
            "Green",
            "Azure",
            "Blue",
            "Purple",
            "Red",
            "Orange",
            "Yellow",
            "White",
        ),
    },
    "Flicker": {
        "decimal": 163,
        "colours": (
            "Red, Green, Blue",
            "Rainbow",
            "Green",
            "Azure",
            "Blue",
            "Purple",
            "Red",
            "Orange",
            "Yellow",
            "White",
        ),
    },
    "Scene": {
        "decimal": 173,
        "colours": (
            "Birthday",
            "Girlfriends",
            "Friends",
            "Workmates",
            "Family",
            "Lover",
        ),
    },
    "Mood": {
        "decimal": 179,
        "colours": (
            "Red",
            "Orange",
            "Yellow",
            "Green",
            "Grass",
            "Azure",
            "Blue",
            "Pink",
            "Gold",
            "Color",
            "True Color",
        ),
    },
    "Selected": {
        "decimal": 191,
        "colours": ("Savasana", "", "Sunrise", "", "Unicorns"),
    },
}

CUSTOM_EFFECT_MODES = [
    ("01", "00"),
    ("02", "00"),
    ("05", "10"),
    ("05", "30"),
    ("05", "40"),
    ("05", "50"),
    ("05", "70"),
    ("05", "80"),
    ("05", "90"),
    ("05", "a0"),
    ("05", "b0"),
    ("05", "c0"),
    ("05", "00"),
    ("05", "20"),
    ("05", "30"),
    ("06", "00"),
    ("06", "10"),
    ("06", "20"),
    ("06", "30"),
    ("06", "50"),
    ("05", "f0"),
    ("05", "10"),
    ("05", "40"),
    ("05", "50"),
    ("06", "60"),
    ("06", "70"),
    ("06", "80"),
]

DEFAULT_EFFECTS = {
    "80s Club": "049a0000",
    "Cherry Blossom": "04940800",
    "Cocktail Parade": "05bd0690",
    "Instagrammer": "03bc0190",
    "Pensieve": "04c40600",
    "Savasana": "04970400",
    "Sunrise": "01c10a00",
    "The Circus": "04810130",
    "Unicorns": "049a0e00",
    "Christmas": "068b0900",
    "Rainbow Flow": "03810690",
    "Music Mode": "07bd0990",
}
